### ISSUE TITLE
Unexpected pagebreak in group header bands

### ISSUE THREAD

**Issue by SofieYesplan** [TIBCOSoftware/jasperreports#420] opened 2024-02-06 10:59 UTC
See added zip file.
Summary of issue:

We have a block of text that we print 10 times in a list (See dataset of list) in the group header band. As you can see when generating the report, this generates a random pagebreak on page 2.

It only occurs when there is whitespace above and below the list, if we eliminate the whitespace, the issue does not occur.

See https://github.com/TIBCOSoftware/jasperreports/issues/419 for similar issue (whitespace mentioned in this issue occurs in the same spot as the pagebreak occurs in this issue).

[unexpected page break in group headers.jrxml.zip](https://github.com/TIBCOSoftware/jasperreports/files/14178551/unexpected.page.break.in.group.headers.jrxml.zip)

**Comment by teodord** [comment] 2024-02-12 12:58
I dont see what do you mean by random page break on page 2. What exactly is random about it?
Please attach a screenshot or something so that we better understand what the problem is.

**Comment by SofieYesplan** [comment] 2024-02-12 13:27
Hi Teodor, here's a pdf generated from this file showing the page break. As mentioned in the other issue, we're working with version 6.20.3 so this may have been fixed in version 6.21?

[report5875552901776236404.pdf](https://github.com/TIBCOSoftware/jasperreports/files/14238910/report5875552901776236404.pdf)

**Comment by teodord** [comment] 2024-02-12 15:04
This seems to be the regression introduced in 6.20.1 and then fixed in 6.20.5:
https://github.com/TIBCOSoftware/jasperreports/commit/1d6476a1a7b0da69dc8aa4d4a51ec67fbd9a03a3

**Closed by teodord** 2024-02-12 15:04 UTC

**Comment by SofieYesplan** [comment] 2024-02-14 10:22
Great, we'll look into updating soon. Thanks for your reply!
