### ISSUE TITLE
Red layer above QR and Barcode in PDF 

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#45] opened 2018-11-16 11:32 UTC
Hi guys, if i open the pdf generated by jasper with an editor like ilustrator i see a red layer above the QR and barcode. Not happening within adobe reader niether browser preview viewer.  
If you print the document from this editor you will print the layer, since the QR or barcode is behind is not printed so they are impossible to read.

do you have any idea how to solve it?

Thanks in advance

**Comment by BernwardWeigand** [comment] 2020-03-09 13:02
I had a similar problem with SVG-images.

The root cause of the problem and and a concept for a solution is described in the [JasperSoft Comunity Forum](https://community.jaspersoft.com/jasperreports-library/issues/11126#comment-855906). It is basically an invisible embedded image of the size of the underlying graphic.

To fix it you have to create your own implementation of the `JRPdfExporter` class, to prevent the call of `getPxImage()`. I implemented a fix and it worked fine.

**Comment by teodord** [comment] 2023-07-21 07:23
Hi,

This has been fixed and will be part of the next release.

Thank you,
Teodor

**Closed by teodord** 2023-07-21 07:23 UTC
