### ISSUE TITLE
Reusing images in pdf

### ISSUE THREAD

**Issue by Canos** [TIBCOSoftware/jasperreports#319] opened 2022-12-20 16:22 UTC
Hi, I have to build a 200 pages pdf.
Every page has the same images but a different text (kind of ticketing app). 

200 pages = 200 tickets = 200 JasperPrint objects

Is there a way to reuse images in the same pdf?

I tried overriding JRPdfExporter caching `cachedImages` property. 
There seems to be a 30% improve in speed, but not in pdf size.
I also checked isUsingCache is enabled in the template.

Thanks

**Comment by teodord** [comment] 2022-12-20 21:51
Hi,

The problem is that the image cache is per JasperPrint. In case of batch PDF export, when multiple JasperPrints are exported in the same PDF, the cache is reset for every JasperPrint and the caching is done only within each individual JasperPrint.
I guess we could introduce a new configuration property to tell the PDF exporter the image caching should be only one for all JasperPrints exported together. For backward compatibility, this setting should be off by default.

Thanks,
Teodor

**Comment by teodord** [comment] 2022-12-21 09:48
Instead of generating multiple JasperPrint objects and batch exporting them to PDF, can you actually fill them together as a report book? Check the book report sample at: https://github.com/TIBCOSoftware/jasperreports/tree/master/jasperreports/demo/samples/book

**Comment by Canos** [comment] 2022-12-21 14:27
Thanks for answering and for your work.
I understand current cache is per JasperPrint, the setting "cache per document" flag you mentioned would be awesome.

Regarding the BookReport sample, sorry in advance, I dont know if I have understood the sample and how to bring the sample to my case. 
I never noticed parts and p:subreportPart exists. so I have to look at the documentation.

I build my JasperPrint objects like below because `params` are not obtained from a single database, but from a bunch of them. So it's difficult to me to detect similarities with BookReport sample.
```java
final JasperPrint jasperPrint = JasperFillManager.fillReport(template, params, new JREmptyDataSource());
```
How would it be in the BookReport sample?

Sorry for such a inconsistent answer, i tried my best

**Comment by teodord** [comment] 2022-12-21 16:06
Book reports are made of parts instead of bands. And a part is like a subreport, just that it produces entire pages instead of being embedded into pages made by a master template.
It enables you to run several reports and concatenate them into a single JasperPrint with a single report execution.

**Comment by teodord** [comment] 2023-07-05 16:17
David, 

Maybe I misunderstood the problem you described, do you really generate 200 different JasperPrint objects and then you batch export them to produce a single PDF?
If you do, then what is the reason for doing that? Can't the 200 pages be the result of running the report only once, with 200 records to iterate through?

Thank you,
Teodor

**Comment by teodord** [comment] 2023-07-10 08:02
We recently made some improvements with respect to the way clipped images and SVG graphics are embedded and reused inside PDF export.
However, it does not solve the fact that images cannot be cached/reused across different JasperPrint objects that get batch exported into a single PDF.
I am not sure such feature would be implemented any time soon, so I am closing this for now.

Thank you,
Teodor

**Closed by teodord** 2023-07-10 08:02 UTC

**Comment by Canos** [comment] 2023-07-10 08:27
Hi Teodor, sorry for not answering, this is attached to my personal email, not business.
First of all thanks for having care of this issue.

We are using jasper to build hunders of pdf tickets.
Every page is a ticket, so it has different data (different locator, different barcodes, qr, different ticket name).
But the images are almost always the same.
Thats why in our edge cases (200/300 hundred tickets) reusing images is a time and memory saving.

So we are concerned because of that.

Can you explain how can we take advantage of the improvements you already made.

**Comment by teodord** [comment] 2023-07-10 10:09
I still do not understand why 200 different tickets, each on a separate page, displaying different data, cannot be generated in a single run. Why should they be generated one by one since eventually you want a single PDF with all of them.

Thank you,
Teodor
