### ISSUE TITLE
 Breakline dissapear on <div> from 6.19.0 into html-styled text field

### ISSUE THREAD

**Issue by colas74** [TIBCOSoftware/jasperreports#289] opened 2022-09-13 07:32 UTC
Hello, 
When I updating jasper version in my java project, I think I found a potential bug or breaking change:
Before version 6.19.0, in Textfield with HTML styling, a breakline was created from each div tag in accordance with HTML syntax.

**Example:**
According this simple template:
![image](https://user-images.githubusercontent.com/15628334/189830310-dad7cb65-a2ad-4049-bb49-c05182a2afa1.png)
And this simple HTML:
```
Line 1
<div>Line 2</div>
<div>Line 3</div>
```

When I merge this template with html text using version 6.18.1, there is the result:
![image](https://user-images.githubusercontent.com/15628334/189831102-779bd167-e267-44e9-8b9f-d2ab4886d057.png)

But if I use version above 6.18.1, the result is widely different:
![image](https://user-images.githubusercontent.com/15628334/189831399-23e56dfa-75c5-4f8e-b4ac-398ba9cc39b1.png)

When I look changelog of 6.19.0, I tried to use 6.19.0 and some old libs from 6.18.1, but no changes at all, it seems that this bug is not throwing from `<dependency>` libs.

I make a minimal reproduction project: 
[minimal-reproduction-eclipse-project.zip](https://github.com/TIBCOSoftware/jasperreports/files/9554534/minimal-reproduction-eclipse-project.zip)
1. Import into eclipse
2. run Main class and look at the console where is the exported PDF path
3. open PDF and notice that HTML text is correct
4. go into pom.xml and use jasperreports version above 6.18.1
5. re-run Main and open exported PDF to see the problem

**Comment by elvisbegovic** [comment] 2022-09-15 07:34
same here and can't find anything related in releases notes : 
![image](https://user-images.githubusercontent.com/2789203/190340406-d5696f94-d5ad-4d88-a36c-e823a0c83671.png)

cc/ @teodord apologize to make noise here but It seems this commit https://github.com/TIBCOSoftware/jasperreports/commit/2c61765f9ea36651338182b1dd5e1490223b3833 change behavior? little out of scope to me and can't find what changed

**Comment by guilhermoMetaway** [comment] 2022-10-06 19:12
It looks like that hapens also with <p> tags,  6.19.x onwards

**Comment by teodord** [comment] 2022-10-12 18:16
This seems to be a regression caused by the changes in the html markup processor when we added support for bulleted and numbered lists. The changes are extensive and investigation needs more time.

**Comment by elvisbegovic** [comment] 2022-10-21 07:45
just for information, thanks to @colas74 , I succeed to reproduce the bug with his [minimal-reproduction-eclipse-project.zip](https://github.com/TIBCOSoftware/jasperreports/files/9554534/minimal-reproduction-eclipse-project.zip)

**Comment by elvisbegovic** [comment] 2023-01-10 13:24
hi @teodord did u have the chance to check whats happening here, thx

**Closed** 2023-02-23 10:39 UTC
